### ISSUE TITLE
Setup deployment 

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#7] opened 2023-10-03 12:54 UTC
We should be able to run Airseeker locally and have it deployed on AWS. This task involves choosing a deployment method (for example, serverless framework or AWS tools or other) and setting it up.

This task to be done after #12.

**Comment by bbenligiray** [comment] 2023-10-06 14:56
This will just be a container, the cloud deployment is out of scope

**Comment by aquarat** [comment] 2023-10-24 14:47
I'm just confirming, if cloud deployment is out of scope+this is a container, then this task is a duplicate of https://github.com/api3dao/airseeker-v2/issues/12 ?

**Comment by bbenligiray** [comment] 2023-10-25 16:35
Looks like it

**Closed by bbenligiray** 2023-10-25 16:35 UTC
